version: '3.7'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/shorty
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
